on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set Firmware Version in File
      run: |
        pwd
        TAG_NAME="${GITHUB_REF##*/}"
        sed -i "s/\\\$TAG:/$TAG_NAME:/" firmware_version
        cat firmware_version
        zip -r nspanel_pro_zigbee_${TAG_NAME}.zip .
    - name: Create Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "fw.zip"
        allowUpdates: true
        draft: true
        makeLatest: true
        name: ${{ github.ref_name }}
        body: ${{ github.ref_name }}
        token: ${{ github.token }}